### ISSUE TITLE
Project template not in New Project selector

### ISSUE THREAD

**Issue by AldoMegabrain** [kellyethridge/SimplyVBUnit#10]
I've installed VB6 on Windows 10, downloaded and installed (as Administrator) SimplyVBUnit, and started a New Project. Unfortunately, the Simply VBUnit Project is not available to be selected.

![image](https://user-images.githubusercontent.com/56831265/74184683-1f4cd100-4c3f-11ea-8bd5-dc953ab1a9db.png)

**Comment by kellyethridge** [comment]
Ya, Windows 10 seems to be hit-n-miss when it comes to getting the project template installed. There are two files that need to be copied to the VB6 projects templates folder:
`SimplyVBUnit Project.vbp`
`frmTestRunner.frm`

They can be found in the `Source/Projects` folder. Copy them to the VB6 Projects template folder and you should see the project available.

**Comment by AldoMegabrain** [comment]
That appears to have done the trick and I now have a SimplyVBUnitTesting project. Thanks for the fast response. 👍
