### ISSUE TITLE
Assertion is not catched, runtime error is shown

### ISSUE THREAD

**Issue by gotoh** [kellyethridge/SimplyVBUnit#14]
When assertion failed on running tests, runner will stop with runtime error dialog.
I expect that this error is catched and counted as 'failed test', and continue next test.
I guess it might be because I'm using Japanese version of VB6 (SP6).

For example, with this test code...
```
Sub Test1()
    Assert.Fail "test for assertion"
End Sub
```
... cause runtime error dialog.
(NOTE: "実行時エラー" means "runtime error")
![runtime-error-by-Assert Fail](https://user-images.githubusercontent.com/105501/75405722-d345a000-5951-11ea-9c13-da379aa39bff.png)

**Comment by kellyethridge** [comment]
Make sure you have your error trapping set to "Break on Unhandled Errors" as show here [https://sourceforge.net/p/simplyvbunit/wiki/Start New Project/](https://sourceforge.net/p/simplyvbunit/wiki/Start%20New%20Project/)

**Comment by gotoh** [comment]
Oh, that is the issue I missed!
Now tests work great by correct option setting.
Thanks!
