### ISSUE TITLE
SimplyVBComp.UIrunner not a loaded class

### ISSUE THREAD

**Issue by abhishekstha98** [kellyethridge/SimplyVBUnit#9]
SimplyVBComp.UIrunner not a loaded class and does not compile

**Comment by kellyethridge** [comment]
What projects are you loading and what are you trying to accomplish?

**Comment by abhishekstha98** [comment]
Im trying to unit test a legacy project which compiles to a .exe file in
vb6 ofcourse. But I have been trying to install the SimplyVBUnit template
And getting the error which says UIRunner was not a loaded class. I found
the UIRunner.ctl and UIRunner.cls files but I am unaware as to where do i
load it.

**Comment by abhishekstha98** [comment]
Im trying to unit test a legacy project which compiles to a .exe file in vb6 ofcourse. But I have been trying to install the SimplyVBUnit template And getting the error which says UIRunner was not a loaded class. I found the UIRunner.ctl and UIRunner.cls files but I am unaware as to where do i load it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kellyethridge** [comment]
Did you use the `SimplyVBUnit` installer? If so, it sounds like the control is not registered. You shouldn't need to try to find `UIRunner.ctl` or `UIRunner.cls` for any reason other than loading the `SimplyVBUnit` source code.

**Comment by abhishekstha98** [comment]
yes, I used the simplyvbunit installer.
then how do i register the control, please help. I am really very new to vb6 and your project seems exciting for unit testing.

**Comment by kellyethridge** [comment]
OK, so if you just run VB6 to the point it shows you a set of empty projects to start from, does it include one for `SimplyVBUnit`? If not, then follow this other thread for help: [Missing SimplyVBUnit Project](https://github.com/kellyethridge/SimplyVBUnit/issues/10)

I just realized that you want to create tests for an EXE. That is a difficult type of project to write tests for. If you're a novice with VB6 I'm unsure it's something you'd want to pursue. I don't want to discourage you from unit-testing, but, it would be a very cumbersome and maybe even impossible project to write tests for.

**Comment by abhishekstha98** [comment]
yeah i read it somewhere in the sourceforge discussion thread but it is needed, there are few forms which are actually testable so I would be importing one forms at a time and testing the important forms. 
the thread that you sent in the previous one is not actually the issue here. the issue actually is : 
![UIRunner](https://user-images.githubusercontent.com/30530429/74211298-62e32180-4cb7-11ea-8203-718d7b1c78d9.JPG)
i dont seem to find any components or references to add in the project.

**Comment by abhishekstha98** [comment]
i can select the SimplyVBUnit project template and then the error above comes up

**Comment by kellyethridge** [comment]
hmmm OK. To register the components manually open a command prompt with Administrative privileges in the `Windows\System32` folder (`Windows\SysWOW64` on 64 bit machines). There should be the following files:
`SimplyVBUnit.Component.ocx`
`SimplyVBUnit.Framework.dll`
`SimplyVBUnitType.tlb`

you should be able to register them using:
`regsvr32 SimplyVBUnit.Component.ocx`
`regsvr32 SimplyVBUnit.Framework.dll`
`regtlib SimplyVBUnitType.tlb`

**Comment by abhishekstha98** [comment]
Thank you Kelly, I tried all that you suggested and even though i couldnt solve the problem, the SimplyVBUnit project being preferred along with DLL files will be a huge let down.

**Comment by kellyethridge** [comment]
Did you simply add the `frmTestRunner.frm` to an existing project? Is the `SimplyVBUnit Component` component referenced in the VB6 Toolbox?

**Comment by abhishekstha98** [comment]
I imported the SimplyVbUnit.Component.ocx from the component menu and it worked, thought it'd be useful for future reference and now whether or not it'll be useful for .exe or not now it'll just work. Thank you for your time.
